#!/bin/bash
AGENT_VERSION=${AGENT_VERSION:-v0.0.9}
IP=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
SHIPYARD_URL="http://$IP:8000"

if [ "$(whoami 2>/dev/null || true)" != 'root' ] ; then
        echo "You must be root to run setup"
        exit 1
fi

case "$(uname -m)" in
	*64)
		;;
	*)
		echo >&2 'Error: you are not using a 64bit platform.'
		echo >&2 'Docker currently only supports 64bit platforms.'
		exit 1
		;;
esac

command -v curl >/dev/null 2>&1 || apt-get install -y curl
command -v docker >/dev/null 2>&1 || curl --silent http://get.docker.io | sh -

if [ -z "$(grep 127.0.0.1:4243 /etc/default/docker)" ] ; then
    sed -i 's/.*DOCKER_OPTS.*/DOCKER_OPTS="-H tcp:\/\/127.0.0.1:4243 -H unix:\/\/var\/run\/docker.sock"/g' /etc/default/docker
    sudo service docker restart
fi

sleep 10

# setup shipyard
DEPLOY_CNT=$(docker run -i -t -d -v /var/run/docker.sock:/docker.sock shipyard/deploy setup)
docker wait $DEPLOY_CNT
# wait for shipyard to start
sleep 10

# setup agent
curl --silent https://github.com/shipyard/shipyard-agent/releases/download/$AGENT_VERSION/shipyard-agent -L -o /usr/local/bin/shipyard-agent
chmod +x /usr/local/bin/shipyard-agent

KEY=$(/usr/local/bin/shipyard-agent -url $SHIPYARD_URL -register 2>&1 | tail -1 | sed 's/.*Key: //g' | tr -d ' ')

echo "Using key $KEY from Shipyard..."

# setup supervisor
apt-get install -y supervisor

cat << EOF > /etc/supervisor/conf.d/shipyard.conf
[program:shipyard-agent]
directory=/tmp
user=root
command=/usr/local/bin/shipyard-agent
    -url $SHIPYARD_URL
    -key $KEY
    autostart=true
    autorestart=true
EOF

supervisorctl update
