#!/bin/bash
TAG=${1:-}
NAME=deploy
REPO=shipyard/shipyard-deploy

if [ -z "$TAG" ]; then
    echo "Usage: $0 <version>"
    echo " Example: $0 latest"
    exit 1
fi

echo "Building $NAME $TAG"
docker build -t $NAME-build -f Dockerfile.build .
docker run --rm -e TAG -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/$REPO $NAME-build make TAG=$TAG build image
